#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "ActiveNSExtensions" \
  --arg udid "$1" \
  --arg filter_extensions_points "$2" \
 '.udid = $udid
  |.request_type = $request_type
  |.filter_extensions_points = ($filter_extensions_points | split(","))
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
