#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "ApplyRedemptionCode" \
  --arg udid "$1" \
  --arg identifier "$2" \
  --arg redemption_code "$3" \
  '.udid = $udid
  |.request_type = $request_type
  |.identifier = $identifier
  |.redemption_code = $redemption_code
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
