#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "ClearPasscode" \
  --arg udid "$1" \
  --arg unlock_token $2 \
  '.udid = $udid
  |.unlock_token = $unlock_token
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
