#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"

force=$3
if [ "$force" == "" ]; then
  force="false"
fi

jq -n \
  --arg request_type "DeleteUser" \
  --arg udid "$1" \
  --arg username "$2" \
  --argjson force_deletion $force \
  '.udid = $udid
  |.username = $username
  |.force_deletion = $force_deletion
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
