#!/bin/bash
source $MICROMDM_ENV_PATH

plan=$3
if [ "$plan" == "" ]; then
  plan="false"
fi
prox=$4
if [ "$prox" == "" ]; then
  prox="false"
fi

endpoint="v1/commands"
jq -n \
  --arg request_type "EraseDevice" \
  --arg udid "$1" \
  --arg pin "$2" \
  --argjson preserve_data_plan $plan \
  --argjson disallow_proximity_setup $prox \
  '.udid = $udid
  |.pin = $pin
  |.preserve_data_plan = $preserve_data_plan
  |.disallow_proximity_setup = $disallow_proximity_setup
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
