#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "EraseDevice" \
  --arg udid "$1" \
  --arg pin "$2" \
  --arg preserve_data_plan $3 \
  --arg disallow_proximity_setup $4 \
  '.udid = $udid
  |.pin = $pin
  |.preserve_data_plan = $preserve_data_plan
  |.disallow_proximity_setup = $disallow_proximity_setup
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
