#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "InstallApplication" \
  --arg udid "$1" \
  --argjson itunes_store_id "$2" \
  '.udid = $udid
  |.request_type = $request_type
  |.itunes_store_id = $itunes_store_id
  '|\
  curl $CURL_OPTS \
    -H "Content-Type: application/json" \
    -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
