#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "ManagedApplicationFeedback" \
  --arg udid "$1" \
  --arg identifiers "$2" \
  --arg delete_feedback $3 \
 '.udid = $udid
  |.request_type = $request_type
  |.identifiers = ($identifiers | split(","))
  |.delete_feedback = $delete_feedback
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
