#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "Restrictions" \
  --arg udid "$1" \
  --arg profile_restrictions $2 \
  '.udid = $udid
  |.profile_restrictions = $profile_restrictions
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
