#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"

# Usage:
# guid - GUID of local account from user_list command device response
# uuid - UUID of a user in micromdm from which to use the password_hash

# Get a password hash from a user specified by uuid
password_hash=$(./tools/api/get_users | jq\
  --arg uuid $3 \
  'select(.users[] as $users | [$uuid] | map([$users[] == .] | any) | all)
   | .users[]
   | .password_hash' | sed 's/"//g')

# Make the SetAutoAdminPassword Request
jq -n \
  --arg request_type "SetAutoAdminPassword" \
  --arg udid "$1" \
  --arg guid "$2" \
  --arg password_hash "$password_hash" \
 '.udid = $udid
  |.request_type = $request_type
  |.guid = $guid
  |.password_hash = $password_hash
  '|\
  curl $CURL_OPTS \
    -H "Content-Type: application/json" \
    -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
