#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"

oroms=$4
if [ "$oroms" == "" ]; then
  oroms="false"
fi

jq -n \
  --arg request_type "SetFirmwarePassword" \
  --arg udid "$1" \
  --arg current_password "$2" \
  --arg new_password "$3" \
  --argjson allow_oroms $oroms \
 '.udid = $udid
  |.request_type = $request_type
  |.current_password = $current_password
  |.new_password = $new_password
  |.allow_oroms = $allow_oroms
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
