#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "UnlockUserAccount" \
  --arg udid "$1" \
  --arg username "$2" \
  '.udid = $udid
  |.username = $username
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
