#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "VerifyFirmwarePassword" \
  --arg udid "$1" \
  --arg password "$2" \
 '.udid = $udid
  |.request_type = $request_type
  |.password = $password
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
